version: 1.0.{build}
image: Visual Studio 2013
configuration: Release
platform: Mixed Platforms
build:
  project: /de4dot.sln
  verbosity: minimal
install:
  - cd de4dot
  - git submodule update --init --recursive
artifacts:
  - path: Release.zip
    name: Release
after_build:
  - 7z a Release.zip C:\projects\de4dot\dnlib\Release\bin\*.*